model:
  name: Recce  # Model Name
  num_classes: 1  # Binary classification for real/fake
config:
  lambda_1: 0.1  # balancing weight for L_r (reconstruction loss)
  lambda_2: 0.1  # balancing weight for L_m (contrastive loss)
  optimizer:
    name: adam
    lr: 0.0002
    weight_decay: 0.00001
  scheduler:
    name: StepLR
    step_size: 22500  # Learning rate decay every 10 epochs
    gamma: 0.5
  resume: False
  resume_best: False
  id: celebdf_recce  # Unique experiment ID
  loss: binary_ce  # Binary cross entropy loss
  metric: Acc  # Main metric for evaluation
  debug: True
  device: "cuda:0"  # Specify the device to use
  ckpt: best_model_1000
data:
  train_batch_size: 32
  val_batch_size: 64
  test_batch_size: 64
  name: CelebDF
  file: "./config/dataset/celeb_df.yml"  # Path to dataset config
  train_branch: "train_cfg"
  val_branch: "test_cfg"
  test_branch: "test_cfg" 